## Activity 01: Use NumPy to compute the Mean, Median, and Variance

In this activity, you will consolidate the skills you've acquired in the last exercise and use NumPy to do some very basic mathematical calculations on our `normal_distribution` dataset.   
NumPy has a consistent API, so it should be rather easy to transfer your knowledge of the mean method to median and variance. 

#### Loading the dataset

In [14]:
# importing the necessary dependencies
import numpy as np

In [15]:
# loading the Dataset
df = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

In [18]:
# looking at the first two rows of the dataset
df[:2]


array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942]])

---

#### Mean

In [24]:
# calculate the mean of the third row
np.mean(df[2])

100.20466135250001

In [33]:
# calculate the mean of the last column
np.mean(df[:,-1])

100.4404927375

In [34]:
# calculate the mean of the intersection of the first 3 rows and first 3 columns
np.mean(df[:3,:3])


97.87197312333333

---

#### Median

In [37]:
# calculate the median of the last row
np.median(df[-1])   

99.18748092

In [39]:
# calculate the median of the last 3 columns
np.median(df[:,-3:])

99.47332349999999

In [44]:
# calculate the median of each row
np.median(df,axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

---

#### Variance

In [45]:
# calculate the variance of each column
np.var(df,axis=0)


array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [49]:
# calculate the variance of the intersection of the last 2 rows and first 2 columns
np.var(df[-2:,:2])

4.674691991769191

The values of the variance might seem a little bit strange at first.   
You can always go back to the topic that gives you a quick statistical overview to recap what you've learned so far.   

> **Note:**   
Just remember, the variance is not the standard deviation.   

Try calculation the standard deviation with NumPy to get a more descriptive value when comparing it to our dataset

In [50]:
# calculate the standard deviation for the dataset
np.std(df)

4.838197554269257

In [51]:
#along rows
np.std(df,axis =1)

array([3.38796579, 4.45771781, 6.22625616, 7.19916062, 4.90725761,
       4.78133105, 4.73259624, 4.11771304, 3.8727956 , 5.35804342,
       3.21184156, 3.95276145, 7.18698395, 4.68331105, 4.13722239,
       4.75079799, 3.32087972, 2.23980965, 4.16611196, 3.37656789,
       3.31368588, 4.3955932 , 3.59622841, 4.05927946])

In [ ]:
#along columns
np.std(df,axis =0)